version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/ubuntu/standard/7.0
      - docker build -t aws/codebuild/standard:7.0 .
      - cd $CODEBUILD_SRC_DIR/al2/x86_64/standard/5.0
      


